//REPORTES
export const GET_REPORTES='GET_REPORTES';
export const ADD_REPORTE='ADD_REPORTE';
export const UPDATE_REPORTE='UPDATE_REPORTE';
export const REPORTES_LOADING='REPORTES_LOADING';


//TICKETS
export const GET_TICKETS='GET_TICKETS';
export const GET_TICKET='GET_TICKET';
export const TICKETS_LOADING='TICKETS_LOADING';
