//REPORTES
export const GET_REPORTES='GET_REPORTES';
export const ADD_REPORTE='ADD_REPORTE';
export const UPDATE_REPORTE='UPDATE_REPORTE';
export const REPORTES_LOADING='REPORTES_LOADING';
export const REPORTES_FILTER='REPORTES_FILTER';
export const SET_REPORTES='SET_REPORTES';


//TICKETS
export const GET_TICKETS='GET_TICKETS';
export const GET_TICKET='GET_TICKET';
export const TICKETS_LOADING='TICKETS_LOADING';
export const CLOSE_TICKET='CLOSE_TICKET';
export const TICKETS_FILTER='TICKETS_FILTER';
export const SET_TICKETS='SET_TICKETS';


//LOGIN
export const LOGIN_USER='LOGIN_USER';
export const LOGIN_LOADING='LOGIN_LOADING';
export const LOGIN_MODAL='LOGIN_MODAL';

//CONFIRMACION
export const CONFIRMACION_MODAL='CONFIRMACION_MODAL';
export const CONFIRMACION_CLOSE='CONFIRMACION_CLOSE';
